### ISSUE TITLE
No set the httpFontsPath

### ISSUE THREAD

**Issue by ceoaliongroo** [gruntjs/grunt-contrib-compass#149]
Hi, 

This happen when i do a 'grunt build'

I tested using httpFontsPath, httpFontsDir in options or dist but no change occurs. Always keep the original path created by yeoman. /bower_components/sass-bootstrap/fonts/

Why do not change to /fonts?

Thanks

```
Gizras-iMac:apps gizra$ npm list grunt-contrib-compass
circuitauction@0.0.0 /Applications/MAMP/htdocs/circuitauction/circuit/apps
└── grunt-contrib-compass@0.7.2 
```

```javascript
// Compiles Sass to CSS and generates necessary files if requested
    compass: {
      options: {
        sassDir: '<%= yeoman.app %>/styles',
        cssDir: '.tmp/styles',
        generatedImagesDir: '.tmp/images/generated',
        imagesDir: '<%= yeoman.app %>/images',
        javascriptsDir: '<%= yeoman.app %>/scripts',
        fontsDir: '<%= yeoman.app %>/styles/fonts',
        importPath: '<%= yeoman.app %>/bower_components',
        httpImagesPath: '/images',
        httpGeneratedImagesPath: '/images/generated',
        relativeAssets: false,
        assetCacheBuster: false
      },
      dist: {
        options: {
          generatedImagesDir: '<%= yeoman.dist %>/images/generated',
          httpFontsPath: '/fonts',
          httpFontsDir: 'fonts'
        }
      },
      server: {
        options: {
          debugInfo: true
        }
      }
    },
```

CSS result:
```css
@font-face{
  font-family:'Glyphicons Halflings';
  src:url(/bower_components/sass-bootstrap/fonts/glyphicons-halflings-regular.eot);
  src:url(/bower_components/sass-bootstrap/fonts/glyphicons-halflings-regular.eot?#iefix) format("embedded-opentype"),
  url(/bower_components/sass-bootstrap/fonts/glyphicons-halflings-regular.woff) format("woff"),
  url(/bower_components/sass-bootstrap/fonts/glyphicons-halflings-regular.ttf) format("truetype"),
  url(/bower_components/sass-bootstrap/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format("svg")
}
```
