### ISSUE TITLE
@each with multiple assignment

### ISSUE THREAD

**Issue by guilhermemarconi** [gruntjs/grunt-contrib-compass#188]
The bash throw me an error when I try to do something like this:

``` scss
@each $animal, $color, $cursor in (puma, black, default),
                                  (sea-slug, blue, pointer),
                                  (egret, white, move) {
  .#{$animal}-icon {
    background-image: url('/images/#{$animal}.png');
    border: 2px solid $color;
    cursor: $cursor;
  }
}
```

I already updated my Sass and Compass gems (that feature was released in version 3.3.0 of Sass on 7 march 2014) and I updated the grunt-contrib-compass too, but I'm still having this error, that expects a "in" after the first variable rather then ", $color, $cursor in (...)".

Am I doing something wrong or maybe the Sass/Compass of this plugin needs update too?
