### ISSUE TITLE
Source map support does not work in chrome

### ISSUE THREAD

**Issue by fizerkhan** [gruntjs/grunt-contrib-compass#58]
I built my sass files with debug flags (debugInfo: true), The output as follows

``` css
@media -sass-debug-info{filename{font-family:file\:\/\/\/Users\/maasaki\/development\/myproject\/app\/styles\/public\.scss}line{font-family:\0000387}}
.masthead .lead {
  color: #747c81;
}
```

Even after i enabled all Sass support flags in Chrome, it does not show scss files (only showing as usual css files). whats wrong with sass output?
