### ISSUE TITLE
Yeoman Webapp, @include/@extends "failing" (but CSS is compiling successfully)

### ISSUE THREAD

**Issue by dwilt** [gruntjs/grunt-contrib-compass#74]
I'm building out a webapp using a directory setup by `yo webapp` and the out-of-the-box grunt-contrib-compass built into Grunt. I've got one file `main.scss` that is importing other files (see my directory structure below) and Grunt is throwing errors that `@extend` and `@include` are failing... but the output CSS is working. See the attached screenshot and the `main.css` output below.
1. If the CSS is compiling correctly, why is grunt-contrib-compass constantly throwing an error?
2. Here's a wild one, look at the `main.css`. Why is the `.sfi-page-header` declaration getting split and put in two places?!!?! (On line 1 and about 75% from the top)
## Here's my styles directory:
- main.scss
- global
  - app.scss
  - header.scss
- includes
  - _vars.scss
  - _mixins.scss
  - _extends.scss
- libs
  - flex.scss
## main.scss

``` SCSS
// Libs
@import "compass";
@import "compass/reset/utilities";
@import "libs/flex";

// 1337 vars & mixins
@import "includes/vars";
@import "includes/mixins";
@import "includes/extends";

@include global-reset;
@import "global/header";
@import "global/app";
```
## header.scss

``` SCSS
.sfi-page-header {
    @extend %white-bg;
    width: 25%;
    box-sizing: border-box;
    border-radius: 0 0 4px 4px;
    padding: 20px;
}

.sfi-page-header-logo-link {
    display: block;
    margin: 20px 30px 30px;
}

.sfi-page-header-logo-image {
    width: 100%;
    display: block;
}

.sfi-page-navigation-about-us-link {
    text-transform: uppercase;
}
```
## app.scss

``` SCSS
.sfi-page-body {
    background-size: cover;
    background-repeat: no-repeat;
    padding: 0 3.125%;
}

.sfi-page-container {
    @include flexbox;
    border: 1px solid blue;
}


```
## _extends.scss

``` SCSS
// Utilities
%reset-list-style {
    margin: 0;
    list-style: none;
}

%visuallyhidden {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute !important;
    width: 1px;
}

%last-child-margin {
    :last-child {
        margin-bottom: 0;
    }
}

// 64i Specific
%white-bg {
    background: rgba(255, 255, 255, .85);
    box-shadow: 0 1px 0 rgba(0, 0, 0, .65);
    border-radius: 4px;
}
```
## flex.scss

``` SCSS
@mixin flexbox {
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flexbox;
    display: flex;
}
```
## main.css (output)

``` CSS
.sfi-page-header {
    background: rgba(255, 255, 255, .85);
    box-shadow: 0 1px 0 rgba(0, 0, 0, .65);
    border-radius: 4px
}

html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
    margin: 0;
    padding: 0;
    border: 0;
    font: inherit;
    font-size: 100%;
    vertical-align: baseline
}

html {
    line-height: 1
}

ol, ul {
    list-style: none
}

table {
    border-collapse: collapse;
    border-spacing: 0
}

caption, th, td {
    text-align: left;
    font-weight: 400;
    vertical-align: middle
}

q, blockquote {
    quotes: none
}

q:before, q:after, blockquote:before, blockquote:after {
    content: "";
    content: none
}

a img {
    border: 0
}

article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section, summary {
    display: block
}

.sfi-page-header {
    width: 25%;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
    border-radius: 0 0 4px 4px;
    padding: 20px
}

.sfi-page-header-logo-link {
    display: block;
    margin: 20px 30px 30px
}

.sfi-page-header-logo-image {
    width: 100%;
    display: block
}

.sfi-page-navigation-about-us-link {
    text-transform: uppercase
}

.sfi-page-body {
    background-size: cover;
    background-repeat: no-repeat;
    padding: 0 3.125%
}

.sfi-page-container {
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-flex;
    display: -ms-flexbox;
    display: -moz-box;
    display: flex;
    border: 1px solid #00f
}
```

![screen shot 2013-08-10 at 12 18 59 am](https://f.cloud.github.com/assets/1065539/942073/0ad00962-0174-11e3-8656-d8cb51460b51.png)
