### ISSUE TITLE
Error: invalid option: --base-path

### ISSUE THREAD

**Issue by dz0ny** [gruntjs/grunt-contrib-compass#8]
Config:

```
compass:
  dev:
    options:
      basePath: "assets"
      require: "zurb-foundation"
      cssDir: "assets/stylesheets"
      sassDir: "assets/sass"
      images: "assets/images"
      fontsDir: "assets/fonts"

  prod:
    options:
      basePath: "assets"
      require: "zurb-foundation"
      cssDir: "assets/stylesheets"
      sassDir: "assets/sass"
      imagesDir: "assets/images"
      fontsDir: "assets/fonts"
      outputStyle: "compact"
```

Grunt error:

```
Running "compass:dev" (compass) task
Error: invalid option: --base-path
```

Compass:

```
compass -v
Compass 0.12.2 (Alnilam)
```

Grunt:

```
grunt --version
grunt-cli v0.1.6
grunt v0.4.0rc7
grunt-contrib-compass ~0.1.1rc7
```
